# Project information
site_name: '新志小站'
site_description: '...'
site_author: 'xinzhi'
# site_url: 'https://aisky.men'

# Repository
repo_name: 'spaceplayer/mkdocs_blog'
repo_url: 'https://github.com/spaceplayer/mkdocs_blog'
edit_uri: 'blob/mkdocs_blog/docs/'

# Copyright
# copyright: 'Copyright &copy; <a href="http://beian.miit.gov.cn">京ICP备19057374号-1</a>'


use_directory_urls: false


nav:
    - '首页': 
      - index.md

    - '算法与数据结构':
      - '算法': 
        - '动态规划': xxx
      - '题目':
        - 'LeetCode题目总结': 算法/LeetCode题目总结.md
        - '剑指offer': 算法/剑指offer.md
        - '面试题总结': 算法/面试题总结.md

    - '推荐系统': 
        - 'FM算法汇总': 推荐系统/FM算法汇总.md
        - '深度学习召回模型': 推荐系统/深度学习召回模型.md

    - '自然语言处理': 
      - '预处理模型': 自然语言处理/BERT及ERNIE学习.md

    - '机器学习': xxx

    - '深度学习': xxx

    - '强化学习': xxx

    - '语言学习':
      - 'C++':
        - 'C++笔记': 语言/CPP笔记.md
      - 'Python':
        - 'Python笔记': 语言/Python笔记.md
        - 'Python高效编程': 语言/Python高效编程.md
      - '设计模式':
        - '设计模式': 语言/设计模式.md
      - '多进程多线程': 语言/多进程多线程.md

    - '常用工具':
      - '如何构建自己的博客': 工具/如何构建自己的博客.md
      - '常用Linux命令': 工具/常用Linux命令.md
      
    - '读书笔记': 
      - '论美国的民主': 读书笔记/论美国的民主.md
    - '随笔记事': xxx
    - '年度计划': xxx



